
version: '3.7'

networks:
  e_coleta_nw:

services:

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks: 
      - e_coleta_nw

  e-coleta-api:
    image: node:alpine
    command: yarn dev
    depends_on:
      - postgres
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8888:8888
      - 9229:9229
    networks: 
      - e_coleta_nw